config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/super_admin'

  get 'dashboard/manager_admin' => 'dashboard#manager_admin'

  root 'home#index'

  resources :inavailabilities
  resources :time_slots
  resources :ratings
  resources :deals
  resources :food_item_add_ons
  resources :food_items
  resources :catering_companies
  resources :addresses
  devise_for :users

  get 'home/create_new_user' => 'home#create_new_user'
  get 'home/edit_user/:id' => 'home#edit_user'

  get '/about/' => 'home#about'
  get '/policy/' => 'home#policy'
  get '/terms/' => 'home#terms'
  get '/contact/' => 'home#contact'

  get '/lang/' => 'home#lang'

  post 'home/save_new_user' => 'home#save_new_user'

  get '/admin/dashboard' => 'dashboard#super_admin'
  get '/admin/dashboard/manage_users' => 'dashboard#super_admin_manage_user'
  get '/admin/dashboard/manage_company' => 'dashboard#super_admin_manage_company'
  get '/admin/dashboard/manage_orders' => 'dashboard#super_admin_manage_orders'

  get '/admin/dashboard/shopkeeper/create_company' => 'dashboard#create_company'
  
  get '/admin/dashboard/shopkeeper/create_food_item' => 'dashboard#create_food_item'
  get '/admin/dashboard/shopkeeper/create_deal' => 'dashboard#create_deal'
  get '/admin/dashboard/shopkeeper/manage_orders' => 'dashboard#manage_orders'
  
  
  get '/admin/dashboard/shopkeeper/manage_addons/' => 'dashboard#manage_addons'
  get '/admin/dashboard/shopkeeper/manage_deals/' => 'dashboard#manage_deals'

  get '/admin/dashboard/shopkeeper/manage_time_slots/' => 'dashboard#manage_time_slots'
  
  get '/serach/results/' => 'dashboard#search_results'

  get '/serach/sm/' => 'dashboard#search_small'

  get '/order/checkout/' => 'dashboard#order_page'
  get '/place/order/:id' => 'dashboard#place_order'
  get '/add_item/' => 'dashboard#add_item_to_cart'
  get '/add_deal/:id/' => 'dashboard#add_deal_to_cart'

  get '/user/account' => 'dashboard#user_account_page', as: :user_account_page

  get '/catering/company/:id' => 'dashboard#cater_page'

  get '/caters/all' => 'dashboard#cater_all'

  get '/select/slot/time/:id' => 'dashboard#select_time_slot'

  get '/order/final/checkout' => 'dashboard#order_final_page'

  post '/order/place/final/' => 'dashboard#place_order_final'

  get '/order/complete/:id' => 'dashboard#complete_order', as: :complete_order

  delete '/admin/dashboard/shopkeeper/deal/delete/:id' => 'dashboard#delete_deal'
  delete '/admin/dashboard/manage_users/delete/:id' => 'dashboard#destroy_user'
  delete '/admin/dashboard/manage_company/delete/:id' => 'dashboard#destroy_comp'
  delete '/admin/dashboard/manage_company/delete/:id' => 'dashboard#destroy_order'
  
  delete '/admin/dashboard/shopkeeper/food_item/delete/:id' => 'dashboard#delete_food_item'

  

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'home#index', as: :unauthenticated_root
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!, except: [:search_results,:place_order, :select_time_slot,:cater_page,:cater_all,:search_small]
  before_action :authorize_as_super_admin, only: [:super_admin]

  def super_admin

  	@users =User.where.not(:level => 1)
  	@c_company = CateringCompany.all

  end



  def create_company
    if current_user.catering_company
      @catering_company = current_user.catering_company
    else
      @catering_company = CateringCompany.new
    end
  end
  
  def create_food_item
      if current_user.catering_company
    @all_food_items = current_user.catering_company.food_items
    @food_item = FoodItem.new
    # @food_item.food_item_add_ons.build
      else
        redirect_to :back, :notice => 'No Company is created yet'
      end

    
  end
  
  

  def destroy_user
  	if current_user.level == 1
  		User.find(params[:id]).destroy
  	end
  	redirect_to action: "super_admin_manage_user"
  end
  
  def delete_food_item
    if current_user.level == 2
      FoodItem.find(params[:id]).destroy
    end
    redirect_to action: "create_food_item"
  end

  def destroy_comp
  	if current_user.level == 1
  		CateringCompany.find(params[:id]).destroy
  	end
  	redirect_to action: "super_admin_manage_company"
  end

  def super_admin_manage_company
  	@c_company = CateringCompany.all
  end

  def super_admin_manage_orders
  	@orders = Order.all
  end



  def manage_orders
    @orders = current_user.catering_company.orders.order('created_at DESC')
  end


  def super_admin_manage_user
    @user = User.new
  	@users = User.where.not(:level => 1)
  end
  
  def manage_deals
    if current_user.catering_company
      @deals = current_user.catering_company.deals
      @deal = Deal.new
    end
  end
  
  def delete_deal
    if current_user.level == 2
      Deal.find(params[:id]).destroy
    end
    redirect_to action: "manage_deals"
  end
  
  def manage_addons
    # @all_food_items_addons = current_user.catering_company.food_item_addons
    @food_item_addons = FoodItem.new
  end

  # def user_id
  # 	params.permit(:id)
  # end

  def manage_time_slots
    @time_slot = TimeSlot.new

  end


  def search_results

  begin
    date = params[:search][:date] || Date.current
    area = params[:search][:area]
    name = params[:search][:caterers]
    @price_min = params[:search][:price_min]
    @price_max = params[:search][:price_max]
    people_min = params[:search][:people_min]
    people_max = params[:search][:people_max]
=begin
   if people_max == "1"

     people_max = "10000"

   end
=end
    female_servers = params[:search][:female_servers]? true:false
    arabic = params[:search][:arabic_speaking]? true:false



    p params.inspect
    @companies =CateringCompany.where("sitting_capacity >= ? OR  sitting_capacity <= ?",people_min.to_i,
                                      people_max.to_i)

    if female_servers and arabic
    @companies = @companies.where(name: name,
                     :city => area,
                     female_servers: female_servers, arabic_speaking: arabic)
    elsif female_servers
    @companies = @companies.where(name: name,
                                  :city => area,
                                  female_servers: female_servers)
    elsif arabic
      @companies = @companies.where(name: name,
                                    :city => area,
                                   arabic_speaking: arabic)
    else
      @companies = @companies.where(name: name,
                                    :city => area)
    end




    #@companies

  rescue


  ensure
    @companies||= CateringCompany.all
  end
    if date
      cart = cookies.fetch(:cart, '{}')
      cart = JSON.parse(cart)
      cart["date"] = date
      cookies[:cart] = JSON.generate(cart)
    end

  end



  def place_order
    @comp = CateringCompany.find params[:id]
    cart = cookies.fetch(:cart, "{}")
    cart = JSON.parse(cart)
    first_time_slot = @comp.available_time_slots(cart["date"].to_date).first
    if first_time_slot


      cart["slot_id"] = cart.fetch("slot_id", first_time_slot.id )
      cookies[:cart] = JSON.generate(cart)  


    end

  end

   def cater_all
     @companies = CateringCompany.all

     cart = cookies.fetch(:cart, '{}')
     cart = JSON.parse(cart)
     cart["date"] ||= Date.current
     cookies[:cart] = JSON.generate(cart)
     @price_min = 0
     @price_max = 1

     render 'search_results'
   end



  def search_small
    name =  params[:search][:name]

    if name
      @companies = CateringCompany.where("lower(name) LIKE ?" , "%#{name.downcase}%")
    else
      @companies = CateringCompany.all
    end

    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    cart["date"] = Date.current
    cookies[:cart] = JSON.generate(cart)
    @price_min = 0
    @price_max = 1

    render 'search_results'

  end



  def add_item_to_cart
    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    food_items = cart.fetch("food_items", [])
    food_items.append(  {item_id: params[:food_item_id], add_on_id: params[:add_on_id], quantity: 1}  )
    cart["food_items"] = food_items
    cookies[:cart] = JSON.generate(cart) 
    
    redirect_to :back
  end

  def add_deal_to_cart
    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    deals = cart.fetch("deals", [])
    deals.append(  {item_id: params[:id], quantity: 1}  )
    cart["deals"] = deals
    cookies[:cart] = JSON.generate(cart)   
    
    redirect_to :back
  end


  def order_page
    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    food_items = cart.fetch("food_items", [])
    food_item_id_list = food_items.collect {|key,value| key["item_id"]}



    deals = cart.fetch("deals", [])
    deals_id_list = deals.collect {|key,value| key["item_id"]}

    @food_items = food_item_id_list.collect {|f| FoodItem.find f} 
    @deals = deals_id_list.collect {|f| Deal.find f} 

  end

  def user_account_page
    @address = Address.new
  end

  def cater_page

    @review = Rating.new
    @comp = CateringCompany.find params[:id]
    begin
    all_ambience = @comp.ratings.pluck(:ambience)
    @ambience = all_ambience.sum / all_ambience.count

    all_food = @comp.ratings.pluck(:food)
    @food = all_food.sum/all_food.count

    all_service = @comp.ratings.pluck(:service)
    @service = all_service.sum/all_service.count

    all_value = @comp.ratings.pluck(:value)
    @value = all_value.sum/all_value.count

    @overall_rating =(@ambience + @food +@service + @value)/4

    total = @comp.ratings.count
    @five = (@comp.ratings.where(:ambience=> 5,:food=>5, :service=>5, :value=>5 ).count/total)*100
    @four =(@comp.ratings.where(:ambience=> 4,:food=>4, :service=>4, :value=>4 ).count/total)*100
    @three= (@comp.ratings.where(:ambience=> 3,:food=>3, :service=>3, :value=>3 ).count/total)*100
    @two = (@comp.ratings.where(:ambience=> 2,:food=>2, :service=>2, :value=>2 ).count/total)*100
    @one = (@comp.ratings.where(:ambience=> 1,:food=>1, :service=>1, :value=>1 ).count/total)*100
    rescue
      end
  end


  def select_time_slot
    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    param_get =  params[:id]
    parsed = param_get.split("&")
    p "**********Got value is #{param_get}"
    p "**********Splited value is is #{parsed.inspect}"
  
    cart["slot_id"] = parsed[0]
    cart["slot_comp_id"] = parsed[1]
    cookies[:cart] = JSON.generate(cart) 

    redirect_to :back
  end



  def order_final_page
    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    cart[:special_request] = params[:special_request]
    cookies[:cart] = JSON.generate(cart)
    food_items = cart.fetch("food_items", [])
    food_item_id_list = food_items.collect {|key,value| key["item_id"]}



    deals = cart.fetch("deals", [])
    deals_id_list = deals.collect {|key,value| key["item_id"]}

    @food_items = food_item_id_list.collect {|f| FoodItem.find f} 
    @deals = deals_id_list.collect {|f| Deal.find f} 
  end

  def place_order_final
    #create order here
    cart = cookies.fetch(:cart, '{}')
    cart = JSON.parse(cart)
    food_items = cart.fetch("food_items", [])
    deals = cart.fetch("deals", [])

    slot = TimeSlot.find_by_id( cart["slot_id"] )

    if not slot.nil? 
      a = Address.new order_params[:address]
      a.user = current_user
      continue = true
      if a.save
        o = Order.new( request_message: cart["special_request"], completed: false,
         user: current_user, catering_company: slot.catering_company, address: a)
      elsif order_params.has_key?(:selected_address)
        o = Order.new( request_message: cart["special_request"], completed: false,
         user: current_user, catering_company: slot.catering_company, address_id:order_params[:selected_address])
      else
        flash[:error] = "Please slect an address or fill the form below"

        # redirect not working properly
        #redirect_to :back
        continue = false
      end
      if continue
        o_item = OrderItem.new( order: o ) 

        food_items.each do |item|
          
          o_i_f = OderItemFood.create( order_item: o_item, food_item_id: item["item_id"].to_i, quanitiy: item["quantity"].to_i )
          if item["add_on_id"]
            OrderFoodItemAddOn.create(oder_item_food_id:item["item_id"].to_i , food_item_add_on_id: item["add_on_id"].to_i)
          end 
        end

        deals.each do |item|
          o_i_f = OderItemDeal.create( order_item: o_item, deal_id: item["item_id"].to_i, quanitiy: item["quantity"].to_i )
        end

    
        o_item.save

        cart = cookies.fetch(:cart, '{}')
        cart = JSON.parse(cart)
        date = cart[:date]

        inavail = Inavailability.create(time_slot: slot, catering_company: slot.catering_company, date: date||Date.current)
            
          o.inavailability_id = inavail.id
           o.save
       
        cookies[:cart] = "{}"

app/helpers/dashboard_helper.rb
module DashboardHelper
	
end

app/views/dashboard/_admin_sidebar.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul style="position: fixed;" class="nav navbar-nav side-nav">
    <li class="active">
      <a href="/admin/dashboard/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
    </li>
    <li>
      <a href="/admin/dashboard/manage_users"><i class="fa fa-fw fa-bar-chart-o"></i> Manage User</a>
    </li>
    <li>
      <a href="/admin/dashboard/manage_company"><i class="fa fa-fw fa-table"></i>Manage Company</a>
    </li>
    <li>
      <a href="/admin/dashboard/manage_orders"><i class="fa fa-fw fa-edit"></i> Manage Orders</a>
    </li>


  </ul>
</div>

app/views/dashboard/create_food_item.html.erb
<div id="wrapper">
<!--

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul style="position: fixed;" class="nav navbar-nav side-nav">
      <li class="active">
        <a href="/admin/dashboard/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
      </li>
      <li>
        <a href="/admin/dashboard/shopkeeper/create_company/"><i class="fa fa-fw fa-bar-chart-o"></i> Manage your Company</a>
      </li>
      <li>
        <a href="/admin/dashboard/shopkeeper/create_food_item"><i class="fa fa-fw fa-table"></i>Manage Food Items</a>
      </li>
      <li>
        <a href="/admin/dashboard/shopkeeper/manage_deals"><i class="fa fa-fw fa-edit"></i> Manage Deals</a>
      </li>
      <li>
        <a href="/admin/dashboard/manage_orders"><i class="fa fa-fw fa-edit"></i> Manage Orders</a>
      </li>


    </ul>
  </div>

-->
  <%= render '/dashboard/manger_sidebar'%>

  <div style="margin-top: 95px;" id="page-wrapper">
    <div class="container-fluid">
      <!-- Page Heading -->
        <div class="row">
          <div class="col-lg-12">
            <h1 class="page-header">
              Dashboard <small>Admin Panel</small>
            </h1>
            <ol class="breadcrumb">
              <li class="active">
                <i class="fa fa-dashboard"></i> Dashboard / Food Item
              </li>
            </ol>
          </div>
        </div>
        <!-- /.row -->

        <!---->


      <style>


          #z_btn{
      margin-bottom: 20px; width: 100%;background: #c6c601;
      border-color: #c6c601;


     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }
#z_btn:hover{
      margin-bottom: 20px; width: 100%;background: #c6c601;
      border-color: #c6c601;


     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }
#z_btn:focus{
      margin-bottom: 20px; width: 100%;background: #c6c601;
      border-color: #c6c601;


     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }

      </style>
          
        <button id="z_btn" class="btn btn-lg"  type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Manage items
        </button>
        <div class="clearfix"></div>
        <div class="collapse" id="collapseExample">
          <div class="">

            <div class="table-responsive">
              <table class="table table-bordered">
                <thead>
                <tr>
                  <th style="text-align: center;">#</th>
                  <th style="text-align: center;">Name</th>
                  <th style="text-align: center;">Description</th>
                  <th style="text-align: center;">Price</th>
                  <th style="text-align: center;">Edit</th>
                  <th style="text-align: center;">Delete</th>
                </tr>
                </thead>



                <tbody>
                <% @all_food_items.each_with_index do |item, index| %>
                    <tr>
                      <td style="text-align: center;"><%= index+1 %></td>
                      <td style="text-align: center;"><%= image_tag(item.pico_url(:standard), class: 'img-thumbnail') %><span style="margin-left: 5px"><%= item.name %></span></td>
                      <td style="text-align: center;"><%= item.description %></td>
                      <td style="text-align: center;"><%= item.price %></td>

                      <td style="text-align: center;"><%= link_to( raw('<span class="fa fa-pencil" />'), edit_food_item_path(item.id) ) %></td>
                      <td style="text-align: center;"><%= link_to( raw('<span class="fa fa-trash-o" />'), {controller: "dashboard", action: "delete_food_item", id: item.id}, method: :delete, data: { confirm: "You sure?" }) %></td>

                    </tr>
                <%end %>
                </tbody>
              </table>
            </div>
            
          </div>
        </div>
        
        <hr>

      <%= render "/dashboard/create_food_item_form" %>



        
        <!---->
        
        
      
        
        
        
        
        
        
        
        
    </div>
  </div>








</div>

app/views/dashboard/manage_deals.html.erb
<div id="wrapper">

 <!-- <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul style="position: fixed;" class="nav navbar-nav side-nav">
      <li class="active">
        <a href="/admin/dashboard/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
      </li>
      <li>
        <a href="/admin/dashboard/shopkeeper/create_company/"><i class="fa fa-fw fa-bar-chart-o"></i> Manage your Company</a>
      </li>
      <li>
        <a href="/admin/dashboard/shopkeeper/create_food_item"><i class="fa fa-fw fa-table"></i>Manage Food Items</a>
      </li>
      <li>
        <a href="/admin/dashboard/manage_deals"><i class="fa fa-fw fa-edit"></i> Manage Deals</a>
      </li>
      <li>
        <a href="/admin/dashboard/manage_orders"><i class="fa fa-fw fa-edit"></i> Manage Orders</a>
      </li>


    </ul>
  </div>
-->
  <%= render '/dashboard/manger_sidebar'%>

  <div style="margin-top: 95px;" id="page-wrapper">
    <div class="container-fluid">
      <!-- Page Heading -->
        <div class="row">
          <div class="col-lg-12">
            <h1 class="page-header">
              Dashboard <small>Admin Panel</small>
            </h1>
            <ol class="breadcrumb">
              <li class="active">
                <i class="fa fa-dashboard"></i> Dashboard / Deals
              </li>
            </ol>
          </div>
        </div>
        <!-- /.row -->

        <!---->


<style>
  .full_btn{
      margin-bottom: 20px; width: 100%;background: #c6c601;
      border-color: #c6c601;


     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }
.full_btn:hover{
      margin-bottom: 20px; width: 100%;background: #c6c601;
      border-color: #c6c601;


     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }
  .full_btn:focus{
      margin-bottom: 20px; width: 100%;background: #c6c601;
      border-color: #c6c601;


     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }

</style>
            <button class="btn btn-lg full_btn btn"  type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              Manage Deal
            </button>


        <div class="clearfix"></div>
        <div class="collapse" id="collapseExample">
          <div class="">

            <div class="table-responsive">
              <table class="table table-bordered">
                <thead>
                <tr>

                  <th>#</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                  <th>Food Items</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </thead>



                <tbody>
                <% if @deals%>
                <% @deals.each_with_index do |deal, index| %>
                    <tr>
                      <td><%= index+1 %></td>
                      <td><%= image_tag(deal.pico_url(:standard), class: 'img-thumbnail') %><span style="margin-left: 5px"><%= deal.name %></span></td>
                      <td><%= deal.description %></td>

                      <td><%= deal.price %></td>
                      <td>
                        <% if deal.food_items%>
                            <% deal.food_items.each do |f|%>
                                <span><%= f.name%></span>
                            <%end%>
                        <%end%>
                      </td>
                      <td><%= link_to( raw('<span class="fa fa-pencil" />'), edit_deal_path(deal.id) ) %></td>
                      <td><%= link_to( raw('<span class="fa fa-trash-o" />'), {controller: "dashboard", action: "delete_deal", id: deal.id}, method: :delete, data: { confirm: "You sure?" }) %></td>

                    </tr>
                <%end %>
                <%end %>
                </tbody>
              </table>
            </div>

          </div>
        </div>
        
        <hr>


      <%= render "/deals/form" %>
        
        <!---->
        
        
      
        
        
        
        
        
        
        
        
    </div>
  </div>








</div>

app/views/dashboard/manage_orders.html.erb
<div id="wrapper">

  <!-- <div class="collapse navbar-collapse navbar-ex1-collapse">
     <ul style="position: fixed;" class="nav navbar-nav side-nav">
       <li class="active">
         <a href="/admin/dashboard/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
       </li>
       <li>
         <a href="/admin/dashboard/manage_users"><i class="fa fa-fw fa-bar-chart-o"></i> Manage User</a>
       </li>
       <li>
         <a href="/admin/dashboard/manage_company"><i class="fa fa-fw fa-table"></i>Manage Company</a>
       </li>
       <li>
         <a href="/admin/dashboard/manage_orders"><i class="fa fa-fw fa-edit"></i> Manage Orders</a>
       </li>


     </ul>
   </div>-->
  <%= render '/dashboard/manger_sidebar'%>















  <div style="margin-top: 95px;" id="page-wrapper">
    <div class="container-fluid">
      <!-- Page Heading -->
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">
            Dashboard <small>Admin Panel</small>
          </h1>
          <ol class="breadcrumb">
            <li class="active">
              <i class="fa fa-dashboard"></i> Dashboard / Orders
            </li>
          </ol>
        </div>
      </div>
      <!-- /.row -->







      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
          <tr>

            <th style="text-align: center;">ID</th>
            <th style="text-align: center;">Status</th>
            <th style="text-align: center;">User</th>
            <th style="text-align: center;">Total</th>
            <th style="text-align: center;">Items</th>
            <th style="text-align: center;">Time and Date</th>
            <th style="text-align: center;"> Address</th>



          </tr>
          </thead>



          <tbody>
          <% if  !@orders.empty?%>
              <% @orders.each_with_index do |order, index| %>
                  <tr>


                    <td style="text-align: center;"> <%=order.id %></td>

                    <td style="text-align: center;">

                      <% if not order.completed %>
                        <%= link_to "Pending", complete_order_path(order.id), class: "btn btn-danger" %>
                          <%else%>
                          <span>Delivered</span>
                      <%end%>
                    </td>
                    
                    



                    <td style="text-align: center;"><%= order.user.email%></td>

                    <td style="text-align: center;"><%= order.total%></td>
                    <td style="text-align: center;">


                      <button type="button" class="btn btn-primary" data-toggle="modal"
                              data-target=<%= "#f_myModal#{index}"%>   >
                        View items
                      </button>
                      <!-- Modal -->
                      <div class="modal fade" id=<%= "f_myModal#{index}"%>      tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                              <h4 class="modal-title" id="myModalLabel"><%= order.request_message%></h4>
                            </div>
                            <div class="modal-body">

                              Food Items:
                              <div class="table-responsive">
                                <table class="table table-bordered">
                                  <thead>
                                  <tr>


                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Add On</th>


                                  </tr>
                                  </thead>


                                  <tbody>

                                  <% order.order_items.each do |o| %>

                                      <tr>
                                      
                                      <% o.oder_item_foods.each do |f_items| %>


                                        <td style="text-align: center;"><%= image_tag(f_items.food_item.pico_url(:thumbnail), class: 'img-thumbnail') %><span style="margin-left: 5px"><%= f_items.food_item.name %></span></td>
                                        <td style="text-align: center;"><%= f_items.food_item.price %></td>

                                        <td style="text-align: center;"><%= f_items.quanitiy %></td>

                                        <td style="text-align: center;">
                                        
                                        <% f_items.food_item_add_ons.each do |aa|%>

                                          | <%= aa.name %> | 
                                        <%end%>
                                        </td>

                                      </tr>
                                        <%end %>
                                      <%end%>

                                  </tbody>
                                </table>
                              </div>


                              Deals :
                              <div class="table-responsive">
                                <table class="table table-bordered">
                                  <thead>
                                  <tr>


                                    <th style="text-align: center;">Name</th>
                                    <th style="text-align: center;">Price</th>
                                    <th style="text-align: center;">Quantity</th>
                                    <th style="text-align: center;">Food Items</th>


                                  </tr>
                                  </thead>


                                  <tbody>

                                  <% order.order_items.each do |o| %>

                                      <tr>
                                      
                                      <% o.oder_item_deals.each do |f_items| %>


                                        <td style="text-align: center;"><%= image_tag(f_items.deal.pico_url(:thumbnail), class: 'img-thumbnail') %><span style="margin-left: 5px"><%= f_items.deal.name %></span></td>
                                        <td style="text-align: center;"><%= f_items.deal.price %></td>

                                        <td style="text-align: center;"><%= f_items.quanitiy %></td>
                                            <td style="text-align: center;"><% f_items.deal.food_items.each do |i| %>
                                                  <%=i.name%>

                                              <%end%>
                                                  </td>

                                        
                                        <%end %>
                                      </tr>

                                      <%end%>

                                  </tbody>
                                </table>
                              </div>




                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>


                    </td>

                    <td style="text-align: center;"><%=  order.inavailability.date.strftime("%B %d %A") %> | <%=  
                    order.inavailability.time_slot.start_time.strftime("%H:%M:%S")      %> - <%=  
                    order.inavailability.time_slot.end_time.strftime("%H:%M:%S")     %></td>

                    <td><p>Street Address 1: <%=order.address.street_address%></p>
                      <% if order.address.street_address_opt%>
                      <p>Street Address 2: <%=order.address.street_address_opt%></p>
                      <%end%>
                      <p>City: <%=order.address.city%></p>
                      <p>Mob: <%=order.address.mobile_number1%></p>
                    </td>
                  </tr>
              <%end %>
          <%end %>
          </tbody>
        </table>
      </div>



    </div>
  </div>








</div>