config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/super_admin'

  get 'dashboard/manager_admin' => 'dashboard#manager_admin'

  root 'home#index'

  resources :inavailabilities
  resources :time_slots
  resources :ratings
  resources :deals
  resources :food_item_add_ons
  resources :food_items
  resources :catering_companies
  resources :addresses
  devise_for :users

  get 'home/create_new_user' => 'home#create_new_user'
  get 'home/edit_user/:id' => 'home#edit_user'

  get '/about/' => 'home#about'
  get '/policy/' => 'home#policy'
  get '/terms/' => 'home#terms'
  get '/contact/' => 'home#contact'

  get '/lang/' => 'home#lang'

  post 'home/save_new_user' => 'home#save_new_user'

  get '/admin/dashboard' => 'dashboard#super_admin'
  get '/admin/dashboard/manage_users' => 'dashboard#super_admin_manage_user'
  get '/admin/dashboard/manage_company' => 'dashboard#super_admin_manage_company'
  get '/admin/dashboard/manage_orders' => 'dashboard#super_admin_manage_orders'

  get '/admin/dashboard/shopkeeper/create_company' => 'dashboard#create_company'
  
  get '/admin/dashboard/shopkeeper/create_food_item' => 'dashboard#create_food_item'
  get '/admin/dashboard/shopkeeper/create_deal' => 'dashboard#create_deal'
  get '/admin/dashboard/shopkeeper/manage_orders' => 'dashboard#manage_orders'
  
  
  get '/admin/dashboard/shopkeeper/manage_addons/' => 'dashboard#manage_addons'
  get '/admin/dashboard/shopkeeper/manage_deals/' => 'dashboard#manage_deals'

  get '/admin/dashboard/shopkeeper/manage_time_slots/' => 'dashboard#manage_time_slots'
  
  get '/serach/results/' => 'dashboard#search_results'

  get '/serach/sm/' => 'dashboard#search_small'

  get '/order/checkout/' => 'dashboard#order_page'
  get '/place/order/:id' => 'dashboard#place_order'
  get '/add_item/' => 'dashboard#add_item_to_cart'
  get '/add_deal/:id/' => 'dashboard#add_deal_to_cart'

  get '/user/account' => 'dashboard#user_account_page', as: :user_account_page

  get '/catering/company/:id' => 'dashboard#cater_page'

  get '/caters/all' => 'dashboard#cater_all'

  get '/select/slot/time/:id' => 'dashboard#select_time_slot'

  get '/order/final/checkout' => 'dashboard#order_final_page'

  post '/order/place/final/' => 'dashboard#place_order_final'

  get '/order/complete/:id' => 'dashboard#complete_order', as: :complete_order

  delete '/admin/dashboard/shopkeeper/deal/delete/:id' => 'dashboard#delete_deal'
  delete '/admin/dashboard/manage_users/delete/:id' => 'dashboard#destroy_user'
  delete '/admin/dashboard/manage_company/delete/:id' => 'dashboard#destroy_comp'
  delete '/admin/dashboard/manage_company/delete/:id' => 'dashboard#destroy_order'
  
  delete '/admin/dashboard/shopkeeper/food_item/delete/:id' => 'dashboard#delete_food_item'

  

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'home#index', as: :unauthenticated_root
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_filter :login_required, :except => [:index,:about,:terms,:policy, :contact,:lang]
	before_action :authorize_as_admin, :only => [:dashboard]

  	def index


		if current_user
			if current_user.level==1
				redirect_to :controller => 'dashboard', :action => 'super_admin'
			elsif current_user.level==2
				redirect_to :controller => 'dashboard', :action => 'manager_admin'
			end
		end
  	end

  	def create_new_user
		# render "devise/registrations/new"
	end
	
	def save_new_user
		@users = User.where.not(level: 1)
		@user = User.new(user_params)
		if @user.save
			redirect_to :controller =>'dashboard', action: 'super_admin_manage_user'
		else

			render '/dashboard/super_admin_manage_user'
		end
	end
  	
  	def edit_user
  		@resource = User.find(params[:id])
  		render "devise/registrations/edit"
  	end

	def dashboard
		if current_user.level == 1
			@users = User.where(:level => 2)
			@companies = CateringCompany.all
			render 'dashboard_super'
		elsif current_user.level == 2
			render 'dashboard_shop_keeper'
		end
	end


		def about

		end

		def policy

		end

		def terms

		end

		def contact

		end

		def lang

			if I18n.locale.to_s == 'en'
				Rails.application.config.lang = 'ar'
			else
				Rails.application.config.lang = 'en'
			end
			redirect_to :back
		end

private
  	def user_params
		params.require(:user).permit(:first_name, :last_name,  :mobile_number1,
																:email, :birthdate, :gender,:level, :occupation, :password, :password_confirmation )
	end


end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  

end

app/views/home/_form.html.erb
<h2>Sign up</h2>

<%= simple_form_for(resource, as: resource_name, url: home_save_new_user_path) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">

      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :mobile_number1 %>

      <%= f.input :email, required: true, autofocus: true %>

      <%= f.input :birthdate, as: :date %>

      <%= f.input :gender %>

      <%= f.hidden_field :level, :value => 2%>


      <%= f.input :occupation %>

      <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
      <%= f.input :password_confirmation, required: true %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Create a member" %>
    </div>
<% end %>

app/views/home/about.html.erb
<%# encoding: utf-8 %>
<div class="container-fluid" id="innerpage">
    <div class="row">
        <div class="innerbanner bx-wrapper">
            <ul class="bxslider">
                <li><img src="images/inner-banner.jpg" class="img-responsive" /></li>
                <li><img src="images/inner-banner.jpg" class="img-responsive" /></li>
            </ul>
            <div class="pageouter">
                <span id="slider-prev">&nbsp;</span> | <span id="slider-next">&nbsp;</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>About Kater</h1>
            <div class="contentbox">
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                <h2>Some Heading</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                <h2>Some Heading</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            </div>

        </div>
    </div>
</div>

<div id="footertop">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-5">
                <h3>Useful Links</h3>
                <div class="links">
                  <a href="/about">About Kater</a>
                  <a href="/policy">Privacy Policy</a>
                  <a href="/terms">Terms & Conditions</a>
                  <a href="/contact">Contact Us</a>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Newsletter</h3>
                <div class="newsletter">
                    <input type="text" class="form-control" placeholder="Your email address" />
                    <i class="fa fa-envelope"></i>
                </div>
            </div>
            <div class="col-md-3">
                <h3>Follow Along</h3>
                <div class="followalong">
                    <a href="#"><i class="fa fa-facebook-f"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-pinterest-p"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="footerbottom">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-sm-7">
                <p>© Kater 605, 6th Floor, Old Education Ministry Building, Mirqab, Kuwait.</p>
                <p>Tel: +965 2239 5022   |   Fax: +965 2239 5022   |   <a href="#">info@kater.com.kw</a></p>
            </div>
            <div class="col-md-6 col-sm-5">
                <div class="payicons">
                    <img src="images/pay-icon-1.jpg" />
                    <img src="images/pay-icon-2.jpg" />
                    <img src="images/pay-icon-3.jpg" />
                    <img src="images/pay-icon-4.jpg" />
                    <img src="images/pay-icon-5.jpg" />
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.bxslider').bxSlider({
            auto: true,
            nextSelector: '#slider-next',
            prevSelector: '#slider-prev',
        });
    });
    var $document = $(document),
            $element = $('#header'),
            elementsidebar = 'headerfixed'

    $(window).scroll(function() {
        $element.toggleClass(elementsidebar, $document.scrollTop() >= 50);
    });
</script>
</body>

app/views/home/contact.html.erb
<%# encoding: utf-8 %>

<div class="container-fluid" id="innerpage">
  <div class="row">
    <div class="innerbanner bx-wrapper">
      <ul class="bxslider">
        <li><img src="images/inner-banner.jpg" class="img-responsive" /></li>
        <li><img src="images/inner-banner.jpg" class="img-responsive" /></li>
      </ul>
      <div class="pageouter">
        <span id="slider-prev">&nbsp;</span> | <span id="slider-next">&nbsp;</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>Get In Touch</h1>
      <div class="contentbox" id="contactform">
        <h2>Form</h2>
        <form class="clearfix">
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="First Name" />
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Last Name" />
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Email" />
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Mobile Number" />
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <textarea class="form-control" rows="6" placeholder="Comments"></textarea>
            </div>
          </div>
          <div class="col-md-12 search-btn">
            <input type="submit" value="SEND" class="btn btn-warning" />
          </div>
        </form>
        <h2>Find</h2>
        <p>Kater 605, Old Ministry of Education Building, Marqab, Kuwait.</p>
        <div class="row">
          <div class="col-md-5">
            <h2>Telephone</h2>
            <p>+965.9729 0717<br />
              +965.6588 3596</p>
          </div>
          <div class="col-md-4">
            <h2>Fax</h2>
            <p>+965.9729 0717<br />
              +965.6588 3596</p>
          </div>
          <div class="col-md-3">
            <h2>Social:</h2>
            <p class="followalong">
              <a href="#"><i class="fa fa-facebook-f"></i></a>
              <a href="#"><i class="fa fa-twitter"></i></a>
              <a href="#"><i class="fa fa-pinterest-p"></i></a>
              <a href="#"><i class="fa fa-linkedin"></i></a>
            </p>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<div id="footertop">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <h3>Useful Links</h3>
        <div class="links">
          <a href="/about">About Kater</a>
          <a href="/policy">Privacy Policy</a>
          <a href="/terms">Terms & Conditions</a>
          <a href="/contact">Contact Us</a>
        </div>
      </div>
      <div class="col-md-4">
        <h3>Newsletter</h3>
        <div class="newsletter">
          <input type="text" class="form-control" placeholder="Your email address" />
          <i class="fa fa-envelope"></i>
        </div>
      </div>
      <div class="col-md-2">
        <h3>Follow Along</h3>
        <div class="followalong">
          <a href="#"><i class="fa fa-facebook-f"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-pinterest-p"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="footerbottom">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-sm-7">
        <p>© Kater 605, 6th Floor, Old Education Ministry Building, Mirqab, Kuwait.</p>
        <p>Tel: +965 2239 5022   |   Fax: +965 2239 5022   |   <a href="#">info@kater.com.kw</a></p>
      </div>
      <div class="col-md-6 col-sm-5">
        <div class="payicons">
          <img src="images/pay-icon-1.jpg" />
          <img src="images/pay-icon-2.jpg" />
          <img src="images/pay-icon-3.jpg" />
          <img src="images/pay-icon-4.jpg" />
          <img src="images/pay-icon-5.jpg" />
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('.bxslider').bxSlider({
            auto: true	 ,
            nextSelector: '#slider-next',
            prevSelector: '#slider-prev',
        });
    });
    var $document = $(document),
            $element = $('#header'),
            elementsidebar = 'headerfixed'

    $(window).scroll(function() {
        $element.toggleClass(elementsidebar, $document.scrollTop() >= 50);
    });
</script>

app/views/home/create_new_user.html.erb
<%= render "form" %>

app/views/home/dashboard_regular.html.erb
<h1>This is Regular User</h1>


<% unless current_user %>
<%= link_to "Sign-In", new_user_session_path %>
    <%else%>
    hello<h3><%= current_user.email%></h3>
<% end%>

app/views/home/dashboard_shop_keeper.html.erb
<div class="panel panel-primary">

	<div class="panel-heading">
	<%if current_user.catering_company%>
	<h3 class="panel-title"><%=current_user.catering_company.name%></h3>
	<%end%>
	</div>
	<div class="panel-body">
		<div class="list-group">
          <% if !current_user.catering_company%>
			<a href="<%= new_catering_company_path %>" class="list-group-item ">
				<h4 class="list-group-item-heading">Create Company</h4>			
			</a>
              <% end%>

			<a href="<%= new_deal_path %>" class="list-group-item ">
				<h4 class="list-group-item-heading">Create Deals</h4>			
			</a>

			<a href="<%= new_food_item_path %>" class="list-group-item ">
				<h4 class="list-group-item-heading">Create Food Item</h4>			
			</a>

			<a href="<%= new_food_item_add_on_path %>" class="list-group-item ">
				<h4 class="list-group-item-heading">Create Food Item Add On</h4>			
			</a>
		</div>
	</div>
	

</div>



<div class="panel panel-primary">

  <div class="panel-heading">
    <h3 class="panel-title">Your food items</h3>
  </div>
  <div class="panel-body">
    <div class="list-group">

    <% if current_user.catering_company %>
      <%current_user.catering_company.food_items.each do |food|%>

      <a href="<%= new_deal_path %>" class="list-group-item ">
        <h4 class="list-group-item-heading"><%=food.name%></h4>
        <h5><%= food.price%></h5>
        <%if(food.deal)%>
        <h5>Deal: <%= food.deal.name%></h5>
      <%end%>

      </a>

     <%end%>
<%end%>

    </div>
  </div>


</div>

app/views/home/dashboard_super.html.erb
<%= link_to "Create New",  {controller: "home", action: "create_new_user"} , class: "btn btn-primary pull-right", role: "button" %>



<div class="clearfix"></div>

<hr>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Edit</th>
      </tr>
    </thead>

    <tbody>
    	<% @users.each_with_index do |user, index| %>
    		<tr>
          <td><%= index+1 %></td>
	    		<td><%= user.first_name %></td>
	    		<td><%= user.last_name %></td>
	    		<td><%= user.email %></td>
	    		<td><%= link_to(raw('<span class="glyphicon glyphicon-pencil" />'), {controller: "home", action: "edit_user", id: user.id})%> </td>

    		</tr>
    	<%end %>
    </tbody>
  </table>
</div>



<div class="clearfix"></div>

<hr>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
    <tr>

      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Contact Number</th>
    </tr>
    </thead>

    <tbody>
    <% @companies.each_with_index do |user, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= user.name %></td>
          <td><%= user.description %></td>
          <td><%= user.contact_number %></td>
          
        </tr>
    <%end %>
    </tbody>
  </table>
</div>

app/views/home/policy.html.erb
<%# encoding: utf-8 %>
<div class="container-fluid" id="innerpage">
  <div class="row">
    <div class="innerbanner bx-wrapper">
      <ul class="bxslider">
        <li><img src="images/inner-banner.jpg" class="img-responsive" /></li>
        <li><img src="images/inner-banner.jpg" class="img-responsive" /></li>
      </ul>
      <div class="pageouter">
        <span id="slider-prev">&nbsp;</span> | <span id="slider-next">&nbsp;</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>Privacy Policy</h1>
      <div class="contentbox">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <h2>Some Heading</h2>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <h2>Some Heading</h2>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
      </div>

    </div>
  </div>
</div>

<div id="footertop">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5">
        <h3>Useful Links</h3>
        <div class="links">
          <a href="/about">About Kater</a>
          <a href="/policy">Privacy Policy</a>
          <a href="/terms">Terms & Conditions</a>
          <a href="/contact">Contact Us</a>
        </div>
      </div>
      <div class="col-md-4">
        <h3>Newsletter</h3>
        <div class="newsletter">
          <input type="text" class="form-control" placeholder="Your email address" />
          <i class="fa fa-envelope"></i>
        </div>
      </div>
      <div class="col-md-3">
        <h3>Follow Along</h3>
        <div class="followalong">
          <a href="#"><i class="fa fa-facebook-f"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-pinterest-p"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="footerbottom">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-sm-7">
        <p>© Kater 605, 6th Floor, Old Education Ministry Building, Mirqab, Kuwait.</p>
        <p>Tel: +965 2239 5022   |   Fax: +965 2239 5022   |   <a href="#">info@kater.com.kw</a></p>
      </div>
      <div class="col-md-6 col-sm-5">
        <div class="payicons">
          <img src="images/pay-icon-1.jpg" />
          <img src="images/pay-icon-2.jpg" />
          <img src="images/pay-icon-3.jpg" />
          <img src="images/pay-icon-4.jpg" />
          <img src="images/pay-icon-5.jpg" />
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.bxslider').bxSlider({
            auto: true	 ,
            nextSelector: '#slider-next',
            prevSelector: '#slider-prev',
        });
    });
    var $document = $(document),
            $element = $('#header'),
            elementsidebar = 'headerfixed'

    $(window).scroll(function() {
        $element.toggleClass(elementsidebar, $document.scrollTop() >= 50);
    });
</script>