config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/super_admin'

  get 'dashboard/manager_admin' => 'dashboard#manager_admin'

  root 'home#index'

  resources :inavailabilities
  resources :time_slots
  resources :ratings
  resources :deals
  resources :food_item_add_ons
  resources :food_items
  resources :catering_companies
  resources :addresses
  devise_for :users

  get 'home/create_new_user' => 'home#create_new_user'
  get 'home/edit_user/:id' => 'home#edit_user'

  get '/about/' => 'home#about'
  get '/policy/' => 'home#policy'
  get '/terms/' => 'home#terms'
  get '/contact/' => 'home#contact'

  get '/lang/' => 'home#lang'

  post 'home/save_new_user' => 'home#save_new_user'

  get '/admin/dashboard' => 'dashboard#super_admin'
  get '/admin/dashboard/manage_users' => 'dashboard#super_admin_manage_user'
  get '/admin/dashboard/manage_company' => 'dashboard#super_admin_manage_company'
  get '/admin/dashboard/manage_orders' => 'dashboard#super_admin_manage_orders'

  get '/admin/dashboard/shopkeeper/create_company' => 'dashboard#create_company'
  
  get '/admin/dashboard/shopkeeper/create_food_item' => 'dashboard#create_food_item'
  get '/admin/dashboard/shopkeeper/create_deal' => 'dashboard#create_deal'
  get '/admin/dashboard/shopkeeper/manage_orders' => 'dashboard#manage_orders'
  
  
  get '/admin/dashboard/shopkeeper/manage_addons/' => 'dashboard#manage_addons'
  get '/admin/dashboard/shopkeeper/manage_deals/' => 'dashboard#manage_deals'

  get '/admin/dashboard/shopkeeper/manage_time_slots/' => 'dashboard#manage_time_slots'
  
  get '/serach/results/' => 'dashboard#search_results'

  get '/serach/sm/' => 'dashboard#search_small'

  get '/order/checkout/' => 'dashboard#order_page'
  get '/place/order/:id' => 'dashboard#place_order'
  get '/add_item/' => 'dashboard#add_item_to_cart'
  get '/add_deal/:id/' => 'dashboard#add_deal_to_cart'

  get '/user/account' => 'dashboard#user_account_page', as: :user_account_page

  get '/catering/company/:id' => 'dashboard#cater_page'

  get '/caters/all' => 'dashboard#cater_all'

  get '/select/slot/time/:id' => 'dashboard#select_time_slot'

  get '/order/final/checkout' => 'dashboard#order_final_page'

  post '/order/place/final/' => 'dashboard#place_order_final'

  get '/order/complete/:id' => 'dashboard#complete_order', as: :complete_order

  delete '/admin/dashboard/shopkeeper/deal/delete/:id' => 'dashboard#delete_deal'
  delete '/admin/dashboard/manage_users/delete/:id' => 'dashboard#destroy_user'
  delete '/admin/dashboard/manage_company/delete/:id' => 'dashboard#destroy_comp'
  delete '/admin/dashboard/manage_company/delete/:id' => 'dashboard#destroy_order'
  
  delete '/admin/dashboard/shopkeeper/food_item/delete/:id' => 'dashboard#delete_food_item'

  

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'home#index', as: :unauthenticated_root
    end
  end

end

app/models/deal.rb
class Deal < ActiveRecord::Base


	attr_accessor :catering_company_id, :food_item_id

	has_and_belongs_to_many :food_items
	belongs_to :catering_company
	belongs_to :order_item


	mount_uploader :pico, PicoUploader


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :authorize_as_shop_admin, only: [:edit, :update,:destroy, :new ]
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
    
    @deals = current_user.catering_company.deals
    render "/dashboard/manage_deals"
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)
    @deal.catering_company= current_user.catering_company
   @deal.food_items = FoodItem.where(id: deal_params[:food_item_ids].compact())

    respond_to do |format|
      if @deal.save
        format.html { redirect_to :controller => 'dashboard', :action => 'manage_deals' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      @deal.food_items = FoodItem.where(id: deal_params[:food_item_ids].compact())
      if @deal.update(deal_params)
        format.html {  redirect_to :controller => 'dashboard', :action => 'manage_deals' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:name, :description,  :price,:pico, {:food_item_ids=>[]}, :pico_cache )
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<% if @deal%>
<%= simple_form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price,  as: :string %>

    <%= f.hidden_field :pico_cache %>
    <%= f.input :pico , as: :file, :label => "Picture" %>

    <%= f.association :food_items, collection: current_user.catering_company.food_items, input_html: { class: 'multiselectuser'}%>
    <span class="text-muted">Press CTRL to select multiple items</span>

  </div>

  <style type="text/css">
  #z_btn2{
      margin-bottom: 20px;background: #c6c601;
      border-color: #c6c601;
      margin-top: 20px;
      margin-bottom: 20px;
     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }
#z_btn2:hover{
      margin-bottom: 20px;background: #c6c601;
      border-color: #c6c601;
 margin-top: 20px;
      margin-bottom: 20px;

     color: #fff;
      font-size: 18px;
      font-weight: 400;
      margin-right: 4%;
      text-transform: uppercase;
  }
  </style>

  <div class="form-actions">
    <%= f.button :submit, "Save", :class=>'btn  ', :id=>'z_btn2' %>
  </div>

<% end %>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>